name: Search Engine Application

on: [push]

jobs:
  build:

    name: Máquina de busca
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validar arquivos composer.[json|lock]
      run:  composer validate

    - name: Instalar dependências
      run:  composer install --prefer-dist --no-progress --no-suggest

    - name: Testes unitários
      run:  composer run-script test

    - name: Executar pesquia
      run:  php app search "iphone"
